### ISSUE TITLE
buttonIndex in UIAlertController

### ISSUE THREAD

**Issue by qiaoyan** [Kosoku/Ditko#9]
buttonIndex = -1 when click cancel button, buttonIndex = 0 when click other button. So current workaround way is [buttonIndex+1]

[UIAlertController KDI_presentAlertControllerWithTitle:@"Sign Out?" message:nil cancelButtonTitle:@"Cancel" otherButtonTitles:@[@"Sign Out"] completion:^(__kindof UIAlertController * _Nonnull alertController, NSInteger buttonIndex) {
            if (alertController.actions[buttonIndex+1].style != UIAlertActionStyleCancel) {
//do something
            }
        }];

**Comment by willbur1984** [comment]
What specifically is the issue? If you want to know whether the cancel button was tapped check for `KDIUIAlertControllerCancelButtonIndex` within the completion block.

```objc
if (buttonIndex == KDIUIAlertControllerCancelButtonIndex) {
    // cancel button was tapped
}
else {
    // check other indexes, starting at 0 - (count of other titles - 1)
}
```

**Comment by qiaoyan** [comment]
understood..
